# Place this in .github/workflows/test-actions.yml
name: Test Auth0 Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # assuming your package.json is in the actions directory
    defaults:
      run:
        working-directory: ./actions

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: node --test
